Feature/change alg
unitatem/mow-anomaly pull request #4
Opened 2018-05-22 10:08 UTC by Verntrax

2018-05-23 22:38 UTC, unitatem requested changes

2018-05-23 22:38 UTC, unitatem commented on src/experiment.R
> +}
\n

2018-05-23 22:38 UTC, unitatem commented on src/grouping_wrapper.R
> +  border = vector("numeric", length=clusters)
move to line 33 (before for loop)

2018-05-23 22:38 UTC, unitatem commented on src/grouping_wrapper.R
> +
rm blank line

2018-05-23 22:38 UTC, unitatem commented on src/main_svm.R
> +message("END")
\n

2018-05-24 10:31 UTC, Verntrax commented on src/experiment.R
> +}
Done

2018-05-24 10:32 UTC, Verntrax commented on src/grouping_wrapper.R
> +  border = vector("numeric", length=clusters)
Done

2018-05-24 10:32 UTC, Verntrax commented on src/grouping_wrapper.R
> +
Done

2018-05-24 10:33 UTC, Verntrax commented on src/main_svm.R
> +message("END")
Done

2018-05-24 15:49 UTC, unitatem approved these changes

2018-05-24 15:49 UTC, merged